<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/

function Headers2Array($response) {
    $headers = array();
    $header_text = substr($response, 0, strpos($response, "\r\n\r\n"));

    foreach (explode("\r\n", $header_text) as $i => $line)
        if ($i === 0)
            $headers['http_code'] = $line;
        else
        {
            list ($key, $value) = explode(': ', $line);

            $headers[$key] = $value;
        }

    return $headers;
}

function request($url, $customHeaders, $customData, $reqType, $returnResult) {
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

    // --- Setup proxy to make Fiddler capture requests ---
    // $proxy = "127.0.0.1:8888";
    // curl_setopt($ch, CURLOPT_PROXY, $proxy);
    // curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);

    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, $reqType);
    
    curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate, br');    

    $requestHeaders = [
                        'cache-control: no-cache',
                        'Pragma: no-cache',
                        'Accept: application/json, text/javascript, */*; q=0.01',
                        'Accept-Encoding: gzip, deflate, br',
                        'Accept-Language: en,vi;q=0.9,fr-FR;q=0.8,fr;q=0.7,en-US;q=0.6,en-GB;q=0.5',
                        'X-Requested-With: XMLHttpRequest',
                        'Content-Type: application/json;charset=UTF-8',
                        'DNT: 1',
                        'Application-Key: 196de13c-e946-4531-98f6-2719ec8405ce',
                        'Application-Version: 7.0.0.4-1',
                        'Channel-Type: MOBILE_WEB',
                        'Environment-Name: Prod',
                        'Jma-Module-Version: 7',
                        'Jma-Version: 7.0.0.39',
                        'Locale: en',
                        'Protocol-Version: 5',
                        'Referer: https://microsoft.gointeract.io/interact/index?interaction=1461173234028-3884f8602eccbe259104553afa8415434b4581-05d1&accountId=microsoft&appkey=196de13c-e946-4531-98f6-2719ec8405ce&token=HR4Rg1',
                        'Run-Mode: FULL',
                        'Security-Token: undefined',
                        'Space-Id: null',
                        'Tenant-Id: microsoft',
                        'Origin: https://microsoft.gointeract.io',
                        'Connection: keep-alive',
                        'Host: microsoft.gointeract.io'
                    ];
    
    if ($customHeaders != null) $requestHeaders = array_merge($requestHeaders, (array) $customHeaders);

    curl_setopt($ch, CURLOPT_HEADER, 1);
    curl_setopt($ch, CURLOPT_HTTPHEADER, $requestHeaders);
    unset($requestHeaders);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $customData);

    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

    $response = curl_exec($ch);

    // --- This line override Fiddler headers, comment this when you're not using Fiddler ---
    //$response = substr($response, strpos($response, "\r\n\r\n") + 4);
    
    // --- Check for HTTP/1.1 100 code, ONLY uncomment this line when you're using Fiddler ---
    //if (strpos((string)$response, "100 Continue")) {$response = substr($response, strpos($response, "\r\n\r\n") + 4);}
    
    if (!curl_errno($ch)) {
        switch ($http_code = curl_getinfo($ch, CURLINFO_HTTP_CODE)) {
            case 100:
                $response = substr($response, strpos($response, "\r\n\r\n") + 4);
            default:
                break;
        }
    } else {
        echo 'Error:' . curl_error($ch);
        curl_close ($ch);
        return null;
    }

    $respHeaders = Headers2Array($response);
    $respBody = substr($response, strpos($response, "\r\n\r\n") + 4);

    curl_close ($ch);

    if ($returnResult) return ['Head' => $respHeaders,
                               'Body' => $respBody];
}

if (isset($_GET['IID'])) {
    $iid = preg_replace("/\D/","",$_GET['IID']);

    if (strlen($iid) == 54 || strlen($iid) == 63) {
        $divider = strlen($iid) / 9;
        echo 'IID Type: ' . $divider . ' digits' . PHP_EOL;
    
        $headers = [];
        $data = null;
        $lnk = 'https://microsoft.gointeract.io/interact/version/2/account/microsoft/interaction/1461173234028-3884f8602eccbe259104553afa8415434b4581-05d1?interaction=1461173234028-3884f8602eccbe259104553afa8415434b4581-05d1&accountId=microsoft&appkey=196de13c-e946-4531-98f6-2719ec8405ce&token=HR4Rg1';
        
        $req = request($lnk,$headers,$data,'POST',true);
    
        $objInstId = $req['Head']['Object-Instance-Id'];
        $usrId = $req['Head']['User-Id'];        
        $lnk = 'https://microsoft.gointeract.io/interact/version/2/account/microsoft/interaction/1461173234028-3884f8602eccbe259104553afa8415434b4581-05d1/' . $objInstId .'/navigation';
        $data = '{"navigationType":"CURRENT"}';
        $headers = ['User-Id: ' . $usrId];
        
        $req = request($lnk,$headers,$data,'POST',true);
    
        $objId = $req['Head']['Object-Id'];
        $objStepId = $req['Head']['Object-Step-Id'];    
        $lnk = 'https://microsoft.gointeract.io/interact/version/2/account/microsoft/interaction/' . $objId . '/' . $objInstId . '/navigation';
        $data = '{"navigationType":"NEXT","param":[{"paramName":"1461173234025-3129f8602eccbe259104553afa8415434b4581-02de","paramValue":"1461173234023-2568f8602eccbe259104553afa8415434b458-10ad"}],"variables":{}}';
        $headers = ['User-Id: ' . $usrId,
                    'Object-Step-Id: ' . $objStepId];
        
        $req = request($lnk,$headers,$data,'POST',true);
    
        //$json = (array) json_decode($req['Body'],true);
        
        //echo $json['interaction']['page']['pageContent']['contentSections'][1]['sectionChoices'][0]['id'];
        
        $objStepId = $req['Head']['Object-Step-Id'];
        
        $data = '{"navigationType":"NEXT","param":[{"paramName":"1461173234025-3148f8602eccbe259104553afa8415434b4581-02f1","paramValue":"' . substr($iid, 0 * $divider, $divider) . '"},{"paramName":"1461173234025-3156f8602eccbe259104553afa8415434b4581-02f9","paramValue":"' . substr($iid, 1 * $divider, $divider) . '"},{"paramName":"1461173234025-3153f8602eccbe259104553afa8415434b4581-02f6","paramValue":"' . substr($iid, 2 * $divider, $divider) . '"},{"paramName":"1461173234025-3150f8602eccbe259104553afa8415434b4581-02f3","paramValue":"' . substr($iid, 3 * $divider, $divider) . '"},{"paramName":"1461173234025-3158f8602eccbe259104553afa8415434b4581-02fb","paramValue":"' . substr($iid, 4 * $divider, $divider) . '"},{"paramName":"1461173234025-3157f8602eccbe259104553afa8415434b4581-02fa","paramValue":"' . substr($iid, 5 * $divider, $divider) . '"},{"paramName":"1461173234025-3155f8602eccbe259104553afa8415434b4581-02f8","paramValue":"' . substr($iid, 6 * $divider, $divider) . '"},{"paramName":"1461173234025-3152f8602eccbe259104553afa8415434b4581-02f5","paramValue":"' . substr($iid, 7 * $divider, $divider) . '"},{"paramName":"1461173234025-3151f8602eccbe259104553afa8415434b4581-02f4","paramValue":"' . substr($iid, 8 * $divider, $divider) . '"},{"paramName":"1461173234025-3154f8602eccbe259104553afa8415434b4581-02f7","paramValue":"' . $iid . '"},{"paramName":"1461173234025-3149f8602eccbe259104553afa8415434b4581-02f2","paramValue":"Submit"}],"variables":{}}';
            
        $headers = ['User-Id: ' . $usrId,
                    'Object-Step-Id: ' . $objStepId];
        
        $req = request($lnk,$headers,$data,'POST',true);
    
        $objStepId = $req['Head']['Object-Step-Id'];
        $data = '{"navigationType":"NEXT","param":[{"paramName":"1461173234025-3162f8602eccbe259104553afa8415434b4581-02ff","paramValue":"0"}],"variables":{}}';
        $headers = ['User-Id: ' . $usrId,
                    'Object-Step-Id: ' . $objStepId];
        
        $req = request($lnk,$headers,$data,'POST',true);
        
        $lnk = 'https://microsoft.gointeract.io/interact/interactionvar/' . $objInstId . '/chConfirmationNum';
        $req = request($lnk,null,null,'GET',true);
        
        echo PHP_EOL . 'CID: ' . PHP_EOL . str_replace('"', '', $req['Body']) . PHP_EOL;
    } else {
        echo 'Wrong IID!!';
    }
} else {
    echo 'No input IID!!' . PHP_EOL;
}

?>